// ALERTS
export const SET_ALERT = 'ALERT/SET_ALERT';
export const REMOVE_ALERT = 'ALERT/REMOVE_ALERT';
export const ALERT_TYPE_DANGER = 'danger';
export const ALERT_TYPE_SUCCESS = 'success';
// USER
export const REGISTER_SUCCESS = 'AUTH/REGISTER_SUCCESS';
export const REGISTER_FAIL = 'AUTH/REGISTER_FAIL';
export const USER_AUTHENTICATION_SUCCESS = 'AUTH/USER_AUTHENTICATION_SUCCESS';
export const USER_AUTHENTICATION_FAIL = 'AUTH/USER_AUTHENTICATION_FAIL';
export const USER_LOGIN_SUCCESS = 'AUTH/USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'AUTH/USER_LOGIN_FAIL';
export const USER_LOGOUT = 'AUTH/USER_LOGOUT';
// PROFILE
export const PROFILE_GET_SUCCESS = 'PROFILE/PROFILE_GET_SUCCESS';
export const PROFILE_GET_ERROR = 'PROFILE/PROFIE_GET_ERROR';
export const PROFILE_EXPERIENCE_DELETE_ERROR =
  'PROFILE/EXPERIENCE/DELETE_ERROR';
export const PROFILE_EXPERIENCE_DELETE_SUCCESS =
  'PROFILE/EXPERIENCE/DELETE_SUCCESS';
export const PROFILE_EDUCATION_DELETE_ERROR = 'PROFILE/EDUCATION/DELETE_ERROR';
export const PROFILE_EDUCATION_DELETE_SUCCESS =
  'PROFILE/EDUCATION/DELETE_SUCCESS';
export const PROFILE_ACCOUNT_DELETE_ERROR = 'PROFILE/ACCOUNT/DELETE_ERROR';
export const PROFILE_ACCOUNT_DELETE_SUCCESS = 'PROFILE/ACCOUNT/DELETE_SUCCES';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE/UPDATE_SUCCES';
export const PROFILE_UPDATE_FAIL = 'PROFILE/UPDATE_FAIL';
export const PROFILE_CREATE_SUCCESS = 'PROFILE/UPDATE_SUCCES';
export const PROFILE_CREATE_FAIL = 'PROFILE/UPDATE_FAIL';
