// Alerts
export const SET_ALERT = 'ALERT/SET_ALERT';
export const REMOVE_ALERT = 'ALERT/REMOVE_ALERT';
export const ALERT_TYPE_DANGER = 'danger';
// Register
export const REGISTER_SUCCESS = 'AUTH/REGISTER_SUCCESS';
export const REGISTER_FAIL = 'AUTH/REGISTER_FAIL';
export const USER_AUTHENTICATION_SUCCESS = 'AUTH/USER_AUTHENTICATION_SUCCESS';
export const USER_AUTHENTICATION_FAIL = 'AUTH/USER_AUTHENTICATION_FAIL';
export const USER_LOGIN_SUCCESS = 'AUTH/USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'AUTH/USER_LOGIN_FAIL';
